(delete-package :me)

(sys.int::cal "home/me/package.lisp")
(sys.int::cal "home/me/line.lisp")
(sys.int::cal "home/me/mark.lisp")
(sys.int::cal "home/me/editor.lisp")
(sys.int::cal "home/me/buffer.lisp")
(sys.int::cal "home/me/point.lisp")
(sys.int::cal "home/me/minibuffer.lisp")
(sys.int::cal "home/me/redisplay.lisp")
(sys.int::cal "home/me/commands.lisp")
(sys.int::cal "home/me/keybindings.lisp")
(sys.int::cal "home/me/main.lisp")
